version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clinicdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
